// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoughDataWebApi.apis.Datas;

#nullable disable

namespace apis.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoughDataWebApi.apis.Models.Goods", b =>
                {
                    b.Property<long>("TGD_PK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TGD_PK"));

                    b.Property<string>("TGD_APPRAI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_AQP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TGD_ATOMIC")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TGD_CERTDA")
                        .HasColumnType("datetime2");

                    b.Property<long?>("TGD_CERTNR")
                        .HasColumnType("bigint");

                    b.Property<long?>("TGD_CERTPK")
                        .HasColumnType("bigint");

                    b.Property<string>("TGD_CLARI2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_CLARI3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_CLARIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_COLOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_COLORE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_COLORF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_COLORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TGD_CRHEIG")
                        .HasColumnType("int");

                    b.Property<string>("TGD_CULET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_CUT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_DOCNR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TGD_DRILLE")
                        .HasColumnType("bit");

                    b.Property<string>("TGD_FLUORE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_GIRDL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_GIRDLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_INFO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_LAB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_LABELC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_MAKE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_MAKEFR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_MAKETO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TGD_MEASU2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TGD_MEASU3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TGD_MEASUR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TGD_ORDER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TGD_PNR")
                        .HasColumnType("int");

                    b.Property<string>("TGD_POLISH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TGD_PRICEE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TGD_PRICEL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TGD_PRICEM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("TGD_REF")
                        .HasColumnType("bigint");

                    b.Property<string>("TGD_SHAPE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_SHAPE1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_SHAPE2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_SHAPE3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_SHAPE4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TGD_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TGD_STONES")
                        .HasColumnType("int");

                    b.Property<string>("TGD_SYMMET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TGD_TABLEW")
                        .HasColumnType("int");

                    b.Property<decimal?>("TGD_TOTDEP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TGD_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TGD_WEIGHT")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TGD_PK");

                    b.ToTable("Goods", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
